MyWebApplication/Controllers/HospitalDataController.cs
using MyWebApplication.Database;
using MyWebApplication.ModelGenerators;
using MyWebApplication.Models;
using MyWebApplication.Models.DbModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MyWebApplication.Controllers
{
    public class HospitalDataController : Controller
    {

        private DatabaseQueryHandler DbQueryHandler;
        // GET: HospitalData

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.DbQueryHandler = DatabaseQueryHandler.Instance;
        }
        
        public ActionResult Overview(int? id)
        {
            if (id == null)
            {
                return View("Error", null);
            }
            
            var model = ModelGenerator.GenerateHospitalDataModel(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Overview(ReviewInformation reviewInformation)
        {
            if (reviewInformation == null || reviewInformation.userName == null)
            {
                return View("Error", null);
            }
            
            int id = reviewInformation.hospitalId;
            ReviewEntry review = CreateReviewEntry(reviewInformation);
            if (review != null)
            {
                this.DbQueryHandler.AddReviewEntry(review);                    
            }

            ModelState.Clear();
            var model = ModelGenerator.GenerateHospitalDataModel(id);
            return View(model);
        }

        private ReviewEntry CreateReviewEntry(ReviewInformation reviewInformation)
        {
            ReviewEntry reviewEntry = new ReviewEntry
            {
                userId = reviewInformation.userName + reviewInformation.hospitalId.ToString(),
                userName = reviewInformation.userName,
                userRating = reviewInformation.Rating,
                userFeedback = reviewInformation.userFeedback,
                hospitalId = reviewInformation.hospitalId,
                isValid = true
            };

            return reviewEntry;
        }
    }
}

MyWebApplication/Controllers/SearchController.cs
using MyWebApplication.Database;
using MyWebApplication.ModelGenerators;
using MyWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWebApplication.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Results(string searchText)
        {
            //HospitalInfoList hospitalInfoList = new HospitalInfoList();
            //HospitalInfo hospitalInfo = new HospitalInfo("Pearless", "Good hospital", "03324256738", "Highland park");
            //hospitalInfoList.HospitalEntryList.Add(hospitalInfo);
            DatabaseQueryHandler dbQueryFetcher = DatabaseQueryHandler.Instance;
            var results = dbQueryFetcher.GetEntriesMatchedByName(searchText);
            return View(results);
        }
    }
}

MyWebApplication/Views/Search/Results.cshtml
@model List<MyWebApplication.Models.DbModels.HospitalDetails>

@{
    ViewBag.Title = "Results";
}

<h2>Results</h2>
@section Styles {
    <link href="@Url.Content("~/Content/Search/results.css?id=0")" rel="stylesheet" type="text/css" />
}

<table class="table">
    
@if (Model != null && Model.Count() > 0) 
{ 
        foreach (var item in Model)
        {
            <div class="entry-display-style">
                    @Html.Raw(item.Name)
                    <p>@Html.Raw(item.Description)</p>
                    @Html.Raw(item.City + "," + item.Country)
                    @Html.Raw(item.ContactInfo)
                    @Html.ActionLink("SeeDetails ...", "Overview", "HospitalData", new { id = item.id, @float = "right" }, null)
            </div>
        @*<tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>*@
        }
}
else
{
    <div class="entry-display-style">
        @Html.Raw("No Results Found")
    </div>
}

</table>